# Generated by Django 4.2.2 on 2023-06-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0005_system_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_systems', models.ManyToManyField(related_name='systems', to='system.system')),
            ],
        ),
    ]
