# Generated by Django 4.2.2 on 2023-06-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_alter_profile_favourite_systems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'الملف الشخصي', 'verbose_name_plural': 'الملفات الشخصية'},
        ),
    ]
