# Generated by Django 4.2.2 on 2023-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=16, verbose_name='العمر'),
        ),
        migrations.AddField(
            model_name='profile',
            name='u_type',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='', max_length=20, verbose_name='النوع'),
            preserve_default=False,
        ),
    ]
