# Generated by Django 4.2.2 on 2023-07-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_field_f_type'),
        ('users', '0004_profile_age_profile_u_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_systems',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='system.system', verbose_name='التقنيات المفضلة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='u_type',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=20, null=True, verbose_name='النوع'),
        ),
    ]
