# Generated by Django 4.2.2 on 2023-07-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_field_f_type'),
        ('users', '0005_alter_profile_favourite_systems_alter_profile_u_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_systems',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='system.system', verbose_name='التقنيات المفضلة'),
        ),
    ]
