# Generated by Django 4.2.2 on 2023-06-16 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'نظام قاعدة بيانات',
                'verbose_name_plural': 'أنظمة قواعد بيانات',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='النوع')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntax', models.TextField(verbose_name='الجملة الأساسية (Syntax)')),
                ('f_type', models.ForeignKey(default='غير معروف', on_delete=django.db.models.deletion.SET_DEFAULT, to='system.type', verbose_name='نوع الحقل')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.system', verbose_name='قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'حقل',
                'verbose_name_plural': 'الحقول',
            },
        ),
    ]
