# Generated by Django 4.2.2 on 2023-06-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'نوع', 'verbose_name_plural': 'أنواع الحقول'},
        ),
    ]
