# Generated by Django 4.2.2 on 2023-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_system_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, verbose_name='اسم الرابط'),
        ),
    ]
