# Generated by Django 4.2.2 on 2023-06-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_system_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='ملخص سريع'),
        ),
    ]
