# Generated by Django 4.2.2 on 2023-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_system_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='f_type',
            field=models.CharField(max_length=75, verbose_name='نوع الحقل'),
        ),
    ]
