# Generated by Django 4.2.2 on 2023-07-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, verbose_name='الجملة الرئيسية')),
                ('sub_heading', models.CharField(max_length=255, verbose_name='الجملة الفرعية')),
                ('btn_text', models.CharField(max_length=100, verbose_name='نص الزر الرئيسي')),
                ('btn_link', models.URLField(verbose_name='رابط الزر الرئيسي')),
            ],
            options={
                'verbose_name': 'الصفحة الرئيسية',
                'verbose_name_plural': 'الصفحة الرئيسية',
            },
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'معلومات'},
        ),
    ]
