# Generated by Django 4.2.2 on 2023-07-04 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('secret', models.TextField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'حساب باي بال',
                'verbose_name_plural': 'حسابات باي بال',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الباقة')),
                ('price', models.IntegerField(verbose_name='سعر الباقة (دولار)')),
                ('description', models.TextField(max_length=200, verbose_name='وصف بسيط للباقة')),
                ('validty', models.IntegerField(default=0, verbose_name='مدة الباقة')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'باقات',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'اشتراكات',
            },
        ),
    ]
