# Generated by Django 4.2.2 on 2023-07-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='وصف بسيط للباقة'),
            preserve_default=False,
        ),
    ]
