# Generated by Django 4.2.2 on 2023-07-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الباقة'),
        ),
    ]
