# Generated by Django 4.2.2 on 2023-07-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('secret', models.TextField()),
                ('access_token', models.TextField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'اشتراكات',
            },
        ),
    ]
