# Generated by Django 4.2.2 on 2023-07-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_paypal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
