# Generated by Django 4.2.2 on 2023-07-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_paypal_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(verbose_name='سعر الباقة (دولار)'),
        ),
    ]
